name: Generate Full Flutter Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - run: flutter create .

      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Generate full flutter structure"
          git push
