name: Generate Full Flutter Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Create Flutter Project
        run: flutter create .

      - name: Get dependencies
        run: flutter pub get
        
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Change App Name to Think Math
        run: |
          sed -i 's/<string name="app_name">.*<\/string>/<string name="app_name">Think Math<\/string>/g' android/app/src/main/res/values/strings.xml

      - name: Commit Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Generate full flutter structure with Think Math name"
          git push
